// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using vulu_yonetimsistemi_api.Data;

#nullable disable

namespace vulu_yonetimsistemi_api.Migrations
{
    [DbContext(typeof(VeriTabaniBaglami))]
    partial class VeriTabaniBaglamiModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("vulu_yonetimsistemi_api.Models.Fatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("OdemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("OdendiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("ServisKaydiId")
                        .HasColumnType("int");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ServisKaydiId")
                        .IsUnique();

                    b.ToTable("Faturalar");
                });

            modelBuilder.Entity("vulu_yonetimsistemi_api.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciAdi")
                        .IsUnique();

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("vulu_yonetimsistemi_api.Models.Musteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("vulu_yonetimsistemi_api.Models.Randevu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RandevuTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ServisKaydiId")
                        .HasColumnType("int");

                    b.Property<int?>("TeknisyenId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId");

                    b.HasIndex("ServisKaydiId");

                    b.HasIndex("TeknisyenId");

                    b.ToTable("Randevular");
                });

            modelBuilder.Entity("vulu_yonetimsistemi_api.Models.ServisKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CihazBilgisi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sorun")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TamamlanmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TeknisyenId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId");

                    b.HasIndex("TeknisyenId");

                    b.ToTable("ServisKayitlari");
                });

            modelBuilder.Entity("vulu_yonetimsistemi_api.Models.Teknisyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uzmanlik")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Teknisyenler");
                });

            modelBuilder.Entity("vulu_yonetimsistemi_api.Models.Fatura", b =>
                {
                    b.HasOne("vulu_yonetimsistemi_api.Models.ServisKaydi", "ServisKaydi")
                        .WithOne("Fatura")
                        .HasForeignKey("vulu_yonetimsistemi_api.Models.Fatura", "ServisKaydiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServisKaydi");
                });

            modelBuilder.Entity("vulu_yonetimsistemi_api.Models.Randevu", b =>
                {
                    b.HasOne("vulu_yonetimsistemi_api.Models.Musteri", "Musteri")
                        .WithMany("Randevular")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vulu_yonetimsistemi_api.Models.ServisKaydi", "ServisKaydi")
                        .WithMany("Randevular")
                        .HasForeignKey("ServisKaydiId");

                    b.HasOne("vulu_yonetimsistemi_api.Models.Teknisyen", "Teknisyen")
                        .WithMany("Randevular")
                        .HasForeignKey("TeknisyenId");

                    b.Navigation("Musteri");

                    b.Navigation("ServisKaydi");

                    b.Navigation("Teknisyen");
                });

            modelBuilder.Entity("vulu_yonetimsistemi_api.Models.ServisKaydi", b =>
                {
                    b.HasOne("vulu_yonetimsistemi_api.Models.Musteri", "Musteri")
                        .WithMany("ServisKayitlari")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vulu_yonetimsistemi_api.Models.Teknisyen", "Teknisyen")
                        .WithMany("ServisKayitlari")
                        .HasForeignKey("TeknisyenId");

                    b.Navigation("Musteri");

                    b.Navigation("Teknisyen");
                });

            modelBuilder.Entity("vulu_yonetimsistemi_api.Models.Teknisyen", b =>
                {
                    b.HasOne("vulu_yonetimsistemi_api.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("vulu_yonetimsistemi_api.Models.Musteri", b =>
                {
                    b.Navigation("Randevular");

                    b.Navigation("ServisKayitlari");
                });

            modelBuilder.Entity("vulu_yonetimsistemi_api.Models.ServisKaydi", b =>
                {
                    b.Navigation("Fatura");

                    b.Navigation("Randevular");
                });

            modelBuilder.Entity("vulu_yonetimsistemi_api.Models.Teknisyen", b =>
                {
                    b.Navigation("Randevular");

                    b.Navigation("ServisKayitlari");
                });
#pragma warning restore 612, 618
        }
    }
}
